### PR TITLE
Added field 19

### PR DESCRIPTION
**Pull request by rainer010**
This field contains the code identifying the country of the acquiring institution.

### CODE REVIEW

**Review by ar — APPROVED** [review]

**Comment by rainer010** [comment]
I checked the ISO-8583 v2003 documentation and the field 19 is not defined. On the other hand, both major card schemes use this field for the same purpose with the same semantic. Hence, I thought it might be good to leave it there. 

What do you think ? @ar

**Comment by rainer010** [comment]
The same reasoning could be applied to the PR #13

**Comment by alcarraz** [comment]
> I checked the ISO-8583 v2003 documentation and the field 19 is not defined. On the other hand, both major card schemes use this field for the same purpose with the same semantic. Hence, I thought it might be good to leave it there.

I see DE 19 as Country code acquiring institution in ISO8583 v2003, in table B.1.

**Comment by alcarraz** [comment]
> I see DE 19 as Country code acquiring institution in ISO8583 v2003, in table B.1. 

So IMHO it is ok to add them, same goes for DE's `009` and `010` of #13, in fact that PR was from the ISO 8583 v2003 spec.

**Comment by rainer010** [comment]
> > I see DE 19 as Country code acquiring institution in ISO8583 v2003, in table B.1.
> 
> So IMHO it is ok to add them, same goes for DE's `009` and `010` of #13, in fact that PR was from the ISO 8583 v2003 spec.

You are right, to summarize the related PRs:

| field | Location in standard spec | PR  |
|------:|---------------------------|-----|
| 9     | Table 3.1, page 22        | #13 |
| 10    | Table 3.1, page 22        | #13 |
| 19    | Table 3.1, page 22        | #20 |

I agree with you, these fields should be added.

**Pull request merged**
